services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - backend

  control_panel:
    build: ./frontend
    command: streamlit run control_panel.py --server.port=8502 --server.address=0.0.0.0
    ports:
      - "8502:8502"
    depends_on:
      - backend